name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.12
  - pandas=2.0.3
  - pip=23.2.1
  - pyarrow=13.0.0
  - pip:
      - wandb==0.15.8
      # - azureml-mlflow
      # - azureml-sdk
