wandb_version: 1

path:
  desc: null
  value: genres_mod.parquet
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.8
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1693131712.719943
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 16
      - 23
      4: 3.10.11
      5: 0.15.8
      8:
      - 5
