name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - notebook
  - seaborn=0.12.2
  - pandas=2.0.3
  - pip=23.2.1
  - pandas-profiling=2.2.0
  - pyarrow=13.0.0
  - pip:
      - wandb==0.15.8
      # - azureml-mlflow
      # - azureml-sdk
